import { GuideClient } from "./guide-client";

export const metadata = {
  title: "Guide des Plantes — PhytoSafeMama Algérie",
  description:
    "Consultez notre guide complet des plantes médicinales et leur sécurité pendant la grossesse.",
};

// ── Fallback data (used when DB is unavailable) ──
const FALLBACK_PLANTS = [
  { id: "1", nameFr: "Fenugrec", nameAr: "حلبة", nameEn: "Fenugreek", nameScientific: "Trigonella foenum-graecum", family: "Fabaceae", toxicityLevel: "DANGER" as const, description: "Le fenugrec est strictement contre-indiqué pendant la grossesse en raison de ses effets potentiellement anti-fertilité et abortifs.", partUsed: "La graine", chemicalComposition: ["Protéines", "Lipides", "C-flavonoïdes", "Sapogénines stéroïdiques"], therapeuticEffects: ["Antidiabétique", "Hypocholestérolémiant"], pregnancySafetyNote: "Strictement contre-indiqué pendant la grossesse en raison de ses effets anti-fertilité et abortifs potentiels.", isAbortifacient: true, isUterotonic: true, symptomNames: ["Diabète gestationnel", "Cholestérol"] },
  { id: "2", nameFr: "Harmel", nameAr: "حرمل", nameEn: "Harmal", nameScientific: "Peganum harmala", family: "Nitrariaceae", toxicityLevel: "DANGER" as const, description: "Le harmel est une plante hautement toxique, strictement contre-indiquée pendant la grossesse en raison de ses propriétés abortives et neurotoxiques.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "Strictement contre-indiqué pendant la grossesse. Propriétés abortives et neurotoxiques connues.", isAbortifacient: true, isUterotonic: true, symptomNames: [] },
  { id: "3", nameFr: "Anis vert", nameAr: "حبة حلاوة", nameEn: "Green Anise", nameScientific: "Pimpinella anisum", family: "Apiaceae", toxicityLevel: "CAUTION" as const, description: "L'anis vert peut être consommé en infusion aqueuse pour une courte durée. L'huile essentielle et les extraits alcooliques sont contre-indiqués.", partUsed: "Le fruit", chemicalComposition: ["Lipides", "Flavonoïdes", "Huile essentielle (E-anéthole)"], therapeuticEffects: ["Traite les troubles digestifs", "Galactagogue"], pregnancySafetyNote: "L'extrait aqueux peut être consommé en infusion pour une courte durée. L'huile essentielle et les extraits alcooliques sont contre-indiqués.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Digestion", "Ballonnements", "Allaitement"] },
  { id: "4", nameFr: "Cumin", nameAr: "كمون", nameEn: "Cumin", nameScientific: "Cuminum cyminum", family: "Apiaceae", toxicityLevel: "SAFE" as const, description: "Le cumin est utilisé comme épice culinaire et est généralement considéré comme sûr pendant la grossesse en quantités alimentaires normales.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Digestion", "Ballonnements"] },
  { id: "5", nameFr: "Camomille du désert", nameAr: "قرطوفة", nameEn: "Desert Chamomile", nameScientific: "Matricaria pubescens", family: "Asteraceae", toxicityLevel: "CAUTION" as const, description: "La camomille du désert est une plante médicinale traditionnelle d'Afrique du Nord. Les données sur sa sécurité pendant la grossesse sont limitées.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: [] },
  { id: "6", nameFr: "Globulaire", nameAr: "تسلغا (زريقة)", nameEn: "Globularia", nameScientific: "Globularia alypum", family: "Plantaginaceae", toxicityLevel: "CAUTION" as const, description: "La globulaire est une plante médicinale traditionnelle du bassin méditerranéen. Les données sur sa sécurité pendant la grossesse sont insuffisantes.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: [] },
  { id: "7", nameFr: "Betterave rouge", nameAr: "شمندر أحمر", nameEn: "Red Beetroot", nameScientific: "Beta vulgaris", family: "Amaranthaceae", toxicityLevel: "SAFE" as const, description: "La betterave rouge est un aliment nutritif, riche en fer et en acide folique, considéré comme sûr et bénéfique pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Anémie", "Fatigue"] },
  { id: "8", nameFr: "Menthe", nameAr: "نعناع", nameEn: "Spearmint", nameScientific: "Mentha spicata", family: "Lamiaceae", toxicityLevel: "SAFE" as const, description: "La menthe verte en infusion légère est considérée comme sûre pendant la grossesse. Elle aide à soulager les nausées et favorise la digestion.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Nausées", "Digestion"] },
  { id: "9", nameFr: "Thym", nameAr: "زعتر", nameEn: "Thyme", nameScientific: "Thymus vulgaris", family: "Lamiaceae", toxicityLevel: "SAFE" as const, description: "Le thym en infusion légère est considéré comme sûr pendant la grossesse. Ses propriétés antiseptiques sont utiles contre les infections respiratoires.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Toux", "Immunité", "Digestion"] },
  { id: "10", nameFr: "Camomille", nameAr: "بابونج", nameEn: "Chamomile", nameScientific: "Matricaria chamomilla", family: "Asteraceae", toxicityLevel: "CAUTION" as const, description: "La camomille est généralement bien tolérée en infusion légère, mais une consommation excessive n'est pas recommandée, surtout au premier trimestre.", partUsed: "Les capitules floraux", chemicalComposition: ["Mucilage", "Coumarines", "Flavonoïdes"], therapeuticEffects: ["Anti-inflammatoire", "Sédative", "Antispasmodique"], pregnancySafetyNote: "Déconseillée à doses excessives et durant les trois premiers mois de grossesse.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Stress", "Insomnie", "Digestion", "Douleurs"] },
  { id: "11", nameFr: "Ail", nameAr: "ثوم", nameEn: "Garlic", nameScientific: "Allium sativum", family: "Amaryllidaceae", toxicityLevel: "SAFE" as const, description: "L'ail est un aliment courant considéré comme sûr pendant la grossesse. Il est associé à un risque réduit d'accouchement prématuré spontané.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Immunité"] },
  { id: "12", nameFr: "Lin", nameAr: "بذور الكتان", nameEn: "Flaxseed", nameScientific: "Linum usitatissimum", family: "Linaceae", toxicityLevel: "CAUTION" as const, description: "Les graines de lin contiennent des phytoestrogènes qui nécessitent une prudence pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Constipation", "Digestion"] },
  { id: "13", nameFr: "Séné", nameAr: "سنا مكي", nameEn: "Senna", nameScientific: "Senna alexandrina", family: "Caesalpiniaceae", toxicityLevel: "DANGER" as const, description: "Le séné n'est pas recommandé pendant la grossesse et l'allaitement en raison du passage possible des dérivés anthraquinoniques à travers le placenta.", partUsed: "Les folioles et le fruit", chemicalComposition: ["Flavonoïdes", "Sennosides"], therapeuticEffects: ["Laxatif stimulant"], pregnancySafetyNote: "Déconseillé pendant la grossesse et l'allaitement en raison du possible passage des dérivés anthraquinoniques à travers le placenta et dans le lait maternel.", isAbortifacient: false, isUterotonic: true, symptomNames: ["Constipation"] },
  { id: "14", nameFr: "Écorce de grenade", nameAr: "قشور الرمان", nameEn: "Pomegranate Bark", nameScientific: "Punica granatum", family: "Lythraceae", toxicityLevel: "CAUTION" as const, description: "L'écorce de grenade contient des alcaloïdes qui peuvent être toxiques à forte dose. La prudence est recommandée pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: [] },
  { id: "15", nameFr: "Lentille rouge", nameAr: "عدس أحمر", nameEn: "Red Lentil", nameScientific: "Lens culinaris", family: "Fabaceae", toxicityLevel: "SAFE" as const, description: "Les lentilles rouges sont un aliment nutritif, riche en protéines, fer et acide folique, particulièrement bénéfique pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Anémie", "Fatigue", "Énergie"] },
  { id: "16", nameFr: "Dattier", nameAr: "تمر", nameEn: "Date Palm", nameScientific: "Phoenix dactylifera", family: "Arecaceae", toxicityLevel: "SAFE" as const, description: "La consommation de dattes pendant les 4 dernières semaines avant l'accouchement réduit significativement le besoin de déclenchement du travail.", partUsed: "Le fruit", chemicalComposition: ["Hydrates de carbone", "Minéraux", "Vitamines"], therapeuticEffects: ["Source énergétique majeure"], pregnancySafetyNote: "La consommation de dattes durant les 4 dernières semaines avant l'accouchement réduit significativement le besoin d'induction du travail.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Fatigue", "Énergie"] },
  { id: "17", nameFr: "Genévrier", nameAr: "عرعار", nameEn: "Juniper", nameScientific: "Juniperus phoenicea", family: "Cupressaceae", toxicityLevel: "DANGER" as const, description: "Le genévrier est contre-indiqué pendant la grossesse en raison de ses propriétés abortives connues.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "Contre-indiqué pendant la grossesse en raison de propriétés abortives et utérotoniques connues.", isAbortifacient: true, isUterotonic: true, symptomNames: [] },
  { id: "18", nameFr: "Gingembre", nameAr: "زنجبيل", nameEn: "Ginger", nameScientific: "Zingiber officinale", family: "Zingiberaceae", toxicityLevel: "CAUTION" as const, description: "Le gingembre est très efficace contre les nausées matinales, mais les doses dépassant les quantités alimentaires habituelles ne sont pas recommandées pendant la grossesse.", partUsed: "Le rhizome", chemicalComposition: ["Amidon", "Oléo-résine (gingérols)", "Flavonoïdes"], therapeuticEffects: ["Antiémétique", "Antioxydant"], pregnancySafetyNote: "Les doses dépassant les quantités alimentaires sont déconseillées pendant la grossesse et l'allaitement.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Nausées", "Digestion", "Ballonnements"] },
  { id: "19", nameFr: "Encens (Oliban)", nameAr: "لبان", nameEn: "Frankincense", nameScientific: "Boswellia sacra", family: "Burseraceae", toxicityLevel: "CAUTION" as const, description: "L'encens est utilisé traditionnellement pour ses propriétés anti-inflammatoires. Les données sur sa sécurité pendant la grossesse sont limitées.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: [] },
  { id: "20", nameFr: "Feuille de vigne rouge", nameAr: "ورق العنب الأحمر", nameEn: "Red Vine Leaf", nameScientific: "Vitis vinifera", family: "Vitaceae", toxicityLevel: "CAUTION" as const, description: "La feuille de vigne rouge est utilisée pour ses propriétés veinotoniques. Les données sur sa sécurité pendant la grossesse sont insuffisantes.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Circulation sanguine"] },
  { id: "21", nameFr: "Orge", nameAr: "شعير", nameEn: "Barley", nameScientific: "Hordeum vulgare", family: "Poaceae", toxicityLevel: "SAFE" as const, description: "L'orge est une céréale nutritive, riche en fibres et en minéraux, considérée comme sûre et bénéfique pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Digestion", "Énergie"] },
  { id: "22", nameFr: "Romarin", nameAr: "إكليل الجبل", nameEn: "Rosemary", nameScientific: "Rosmarinus officinalis", family: "Lamiaceae", toxicityLevel: "CAUTION" as const, description: "Le romarin en quantités culinaires est généralement toléré. L'huile essentielle et les doses thérapeutiques sont déconseillées pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Digestion", "Fatigue"] },
  { id: "23", nameFr: "Lavande", nameAr: "خزامى", nameEn: "Lavender", nameScientific: "Lavandula angustifolia", family: "Lamiaceae", toxicityLevel: "CAUTION" as const, description: "La lavande en infusion légère est généralement bien tolérée. L'huile essentielle est déconseillée pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Stress", "Insomnie"] },
  { id: "24", nameFr: "Cannelle", nameAr: "قرفة", nameEn: "Cinnamon", nameScientific: "Cinnamomum verum", family: "Lauraceae", toxicityLevel: "DANGER" as const, description: "La cannelle est absolument contre-indiquée pendant la grossesse et en cas d'ulcères gastriques.", partUsed: "L'écorce", chemicalComposition: ["Huile essentielle (cinnamaldéhyde, eugénol)", "Flavonoïdes", "Coumarine"], therapeuticEffects: ["Antibactérienne", "Antifongique"], pregnancySafetyNote: "Contre-indication absolue pendant la grossesse ainsi qu'en cas d'ulcère gastrique.", isAbortifacient: true, isUterotonic: false, symptomNames: ["Immunité"] },
  { id: "25", nameFr: "Armoise blanche", nameAr: "الشيح", nameEn: "White Wormwood", nameScientific: "Artemisia herba-alba", family: "Asteraceae", toxicityLevel: "DANGER" as const, description: "L'armoise blanche est strictement contre-indiquée pendant la grossesse. Elle contient de la thuyone aux propriétés abortives et neurotoxiques.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "Strictement contre-indiquée pendant la grossesse en raison de la thuyone aux propriétés abortives et neurotoxiques documentées.", isAbortifacient: true, isUterotonic: true, symptomNames: [] },
  { id: "26", nameFr: "Huile d'olive", nameAr: "زيت الزيتون", nameEn: "Olive Oil", nameScientific: "Olea europaea", family: "Oleaceae", toxicityLevel: "SAFE" as const, description: "L'huile d'olive est très bénéfique et sûre pendant la grossesse. Elle réduit le risque de reflux gastro-œsophagien et favorise la digestion.", partUsed: "Les fruits", chemicalComposition: ["Eau", "Glucides", "Lipides"], therapeuticEffects: ["Réduit le risque de reflux gastro-œsophagien", "Favorise la digestion"], pregnancySafetyNote: "Bénéfique pendant la grossesse.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Digestion", "Reflux gastrique"] },
  { id: "27", nameFr: "Oignon", nameAr: "بصل", nameEn: "Onion", nameScientific: "Allium cepa", family: "Amaryllidaceae", toxicityLevel: "SAFE" as const, description: "L'oignon est un aliment courant considéré comme sûr pendant la grossesse. Riche en quercétine aux propriétés anti-inflammatoires.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "", isAbortifacient: false, isUterotonic: false, symptomNames: ["Immunité"] },
  { id: "28", nameFr: "Graines de fenouil", nameAr: "زريعة البسباس", nameEn: "Fennel Seeds", nameScientific: "Foeniculum vulgare", family: "Apiaceae", toxicityLevel: "DANGER" as const, description: "Les graines de fenouil contiennent de l'estragole, potentiellement cancérigène et œstrogénique. L'huile essentielle est contre-indiquée pendant la grossesse.", partUsed: "", chemicalComposition: [], therapeuticEffects: [], pregnancySafetyNote: "L'huile essentielle est contre-indiquée pendant la grossesse en raison des effets œstrogéniques de l'estragole.", isAbortifacient: false, isUterotonic: true, symptomNames: ["Digestion", "Ballonnements"] },
  { id: "29", nameFr: "Menthe pouliot", nameAr: "فليو", nameEn: "Pennyroyal Mint", nameScientific: "Mentha pulegium", family: "Lamiaceae", toxicityLevel: "DANGER" as const, description: "La menthe pouliot possède une longue tradition d'utilisation comme abortif. La pulégone qu'elle contient est hépatotoxique et stimule les muscles utérins.", partUsed: "Parties aériennes et huile essentielle", chemicalComposition: ["Huiles volatiles : pulégone, alpha-pinène, bêta-pinène, limonène, menthone, pipériténone", "Tanins", "Paraffines"], therapeuticEffects: ["Tonique digestif", "Soulage les flatulences et coliques", "Stimule les muscles utérins"], pregnancySafetyNote: "Possède une longue tradition d'utilisation comme abortif. Strictement contre-indiquée pendant la grossesse.", isAbortifacient: true, isUterotonic: true, symptomNames: ["Digestion"] },
  { id: "30", nameFr: "Origan", nameAr: "زعتر بري", nameEn: "Oregano", nameScientific: "Origanum vulgare", family: "Lamiaceae", toxicityLevel: "CAUTION" as const, description: "L'origan ne doit pas être utilisé comme médicament durant la grossesse. L'huile essentielle est déconseillée par voie interne.", partUsed: "Parties aériennes et huile essentielle", chemicalComposition: ["Huile volatile : carvacrol, thymol, bêta-bisabolène, caryophyllène, linalol, bornéol", "Tanins", "Résine", "Stérols", "Flavonoïdes"], therapeuticEffects: ["Antiseptique puissant", "Activité contre bactéries et champignons", "Utilisé dans les infections digestives et respiratoires"], pregnancySafetyNote: "Ne pas utiliser comme médicament durant la grossesse. L'huile essentielle est déconseillée par voie interne.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Immunité", "Digestion", "Douleurs"] },
  { id: "31", nameFr: "Safran", nameAr: "زعفران", nameEn: "Saffron", nameScientific: "Crocus sativa", family: "Iridaceae", toxicityLevel: "DANGER" as const, description: "Des doses supérieures à 10 g de safran peuvent provoquer un avortement et entraîner plusieurs effets secondaires graves.", partUsed: "Le stigmate", chemicalComposition: ["Crocines (glucosides caroténoïdes)", "Huile volatile (safranal)", "Substances amères"], therapeuticEffects: ["Neuroprotecteur", "Antidépresseur", "Antispasmodique", "Tonique cardiaque"], pregnancySafetyNote: "Des doses supérieures à 10 g peuvent provoquer un avortement.", isAbortifacient: true, isUterotonic: true, symptomNames: ["Stress"] },
  { id: "32", nameFr: "Verveine", nameAr: "اللويزة", nameEn: "Vervain", nameScientific: "Verbena officinalis", family: "Verbenaceae", toxicityLevel: "DANGER" as const, description: "La verveine peut stimuler l'utérus et présenter un effet abortif. Elle est déconseillée pendant la grossesse.", partUsed: "Parties aériennes récoltées pendant la floraison", chemicalComposition: ["Iridoïdes : verbenaline, verbenine, hastatoside", "Polyphénols : verbascoside, aucubine, lutéoline 7-diglucuronide"], therapeuticEffects: ["Expectorant", "Antitussif", "Anti-inflammatoire", "Anti-gastritique"], pregnancySafetyNote: "La verveine peut stimuler l'utérus et présenter un effet abortif. Déconseillée pendant la grossesse.", isAbortifacient: true, isUterotonic: true, symptomNames: ["Toux"] },
  { id: "33", nameFr: "Giroflier", nameAr: "قرنفل", nameEn: "Clove", nameScientific: "Caryophyllus aromaticus", family: "Myrtaceae", toxicityLevel: "DANGER" as const, description: "Le giroflier peut stimuler les contractions utérines. Son huile essentielle est strictement déconseillée pendant la grossesse.", partUsed: "Le bouton floral séché (clou)", chemicalComposition: ["Huile essentielle riche en eugénol", "β-caryophyllène", "Composés terpéniques, aromatiques, aliphatiques et hétérocycliques", "Hétérosides de chromones"], therapeuticEffects: ["Antalgique contre les douleurs dentaires et céphalées", "Antiseptique buccal", "Troubles digestifs : ballonnements, flatulences"], pregnancySafetyNote: "Le giroflier peut stimuler les contractions utérines. Son huile essentielle est strictement déconseillée pendant la grossesse.", isAbortifacient: false, isUterotonic: true, symptomNames: ["Douleurs", "Digestion"] },
  { id: "34", nameFr: "Sauge officinale", nameAr: "الميرامية", nameEn: "Sage", nameScientific: "Salvia officinalis", family: "Lamiaceae", toxicityLevel: "CAUTION" as const, description: "La sauge officinale contient de la thuyone, une substance neurotoxique. À utiliser avec prudence pendant la grossesse, surtout sous forme d'huile essentielle.", partUsed: "Les feuilles et les parties aériennes", chemicalComposition: ["Huile essentielle : thuyone, cinéole, camphre", "Flavonoïdes", "Tanins", "Acides phénoliques"], therapeuticEffects: ["Réduit le reflux gastro-œsophagien", "Facilite la digestion", "Antiseptique et anti-inflammatoire"], pregnancySafetyNote: "À utiliser avec prudence pendant la grossesse, surtout sous forme d'huile essentielle.", isAbortifacient: false, isUterotonic: false, symptomNames: ["Digestion", "Reflux gastrique"] },
  { id: "35", nameFr: "Rue", nameAr: "الفيجل", nameEn: "Rue", nameScientific: "Ruta graveolens", family: "Rutaceae", toxicityLevel: "DANGER" as const, description: "La rue est contre-indiquée pendant la grossesse en raison de son effet abortif et stimulant utérin bien documenté.", partUsed: "Les parties aériennes", chemicalComposition: ["Huile essentielle", "Flavonoïdes", "Alcaloïdes", "Furocoumarines"], therapeuticEffects: ["Antispasmodique", "Digestive", "Stimule les menstruations"], pregnancySafetyNote: "Contre-indiquée pendant la grossesse en raison de son effet abortif et stimulant utérin.", isAbortifacient: true, isUterotonic: true, symptomNames: [] },
];

const FALLBACK_SYMPTOMS = [
  "Nausées", "Stress", "Insomnie", "Douleurs", "Digestion", "Fatigue",
  "Immunité", "Ballonnements", "Toux", "Constipation", "Anémie",
  "Énergie", "Allaitement", "Circulation sanguine", "Reflux gastrique",
  "Diabète gestationnel", "Cholestérol"
];

export default async function GuidePage() {
  let plants = FALLBACK_PLANTS;
  let symptomList = FALLBACK_SYMPTOMS;

  try {
    const { prisma } = await import("@/lib/prisma");
    const dbPlants = await prisma.plant.findMany({
      orderBy: { nameFr: "asc" },
      include: { symptoms: { include: { symptom: true } } },
    });

    if (dbPlants.length > 0) {
      plants = dbPlants.map((p) => ({
        id: p.id,
        nameFr: p.nameFr,
        nameAr: p.nameAr,
        nameEn: p.nameEn,
        nameScientific: p.nameScientific,
        family: p.family,
        toxicityLevel: p.toxicityLevel,
        description: p.description,
        partUsed: p.partUsed,
        chemicalComposition: p.chemicalComposition,
        therapeuticEffects: p.therapeuticEffects,
        pregnancySafetyNote: p.pregnancySafetyNote,
        isAbortifacient: p.isAbortifacient,
        isUterotonic: p.isUterotonic,
        symptomNames: p.symptoms.map((ps) => ps.symptom.name),
      }));
    }

    const dbSymptoms = await prisma.symptom.findMany({ orderBy: { name: "asc" } });
    if (dbSymptoms.length > 0) {
      symptomList = dbSymptoms.map((s) => s.name);
    }
  } catch {
    console.warn("⚠️ Database unavailable, using fallback data");
  }

  return <GuideClient plants={plants} symptoms={symptomList} />;
}
